# Generated by Django 3.0.4 on 2020-03-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='lastUpdatedDate',
            field=models.DateTimeField(),
        ),
    ]
