# Generated by Django 3.0.4 on 2020-03-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200314_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notemodel',
            name='lastUpdatedDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notemodel',
            name='newUpdatedDate',
            field=models.DateField(),
        ),
    ]
